#pragma once
#include <esp_adc/adc_oneshot.h>


// ATTENUATED VOLTAGE (0 - 3.3V) BY DEFAULT
#define D_P_ADC_ONESHOT_CHANNELS_ATTEN ADC_ATTEN_DB_12
// BIT RESOLUTION 12 BITS BY DEFAULT
#define D_P_ADC_ONESHOT_CHANNELS_BITWIDTH ADC_BITWIDTH_12

// VALUES TRADUCTION
#define D_P_ADC_ONESHOT_CHANNELS_VOLTAGE_MAX 3.3f
#define D_P_ADC_ONESHOT_CHANNELS_LECTURE_MAX 4096.0f

// CONFIG LOW LEVEL

// ULTRA LOW POWER DISABLE BY DEFAULT
#define D_P_ADC_ONESHOT_ULP_MODE ADC_ULP_MODE_DISABLE
// DEFAULT CLOCK
#define D_P_ADC_ONESHOT_CLK_SRC ADC_RTC_CLK_SRC_DEFAULT